(function ($) {
	// Autocomplete Search Field
	var availableTags = ["Cancer","Cancer care","Cancer control","Breast cancer","Colorectal cancer","Research","Researchers","Practitioners","Discussions","Cyber-Seminars","Featured R2R Partner","Learning Communities","Events","Community","Precision Medicine","Interventions","Stephenie Lemon","Lori Pbert","Tobacco","Conference","Evidence","Policy ","Practice","Tutorial","Delivery","Evidence-based","Randomized trials","Implementation studies","SMART","HPV","Vaccine","LGBT","Disparities","Cultural Competency","Screening","RTIPs","Decision-making","De-Implementation","Survivorship","Effectiveness","Clinical","Clinical Effectiveness","Healthy Eating","Latino","Suellen Hopfer","Hybrid Designs","Storytelling","HINTS","Education","Coalition","Public Health ","Training Modules","Veteran","Taxes","International Perspectives","Dissemination","Implementation","NIH","Training","Oncology","Mentor","Mentorship","Collaboration","Patient","Modeling","Impact","Radiation","Peer-to-peer","Children","Survivorship","Survivorship Care","Social Media","Skin Cancer","Health","Health Disparities","Dianne Neumark-Sztainer","Smoke-free Laws","Obesity","Communication Science","Risk Assessment","Healthcare","Exercise","Sanja Percac-Lima","Practice","Environmental Change","Sherry Lebed Davis","Genomics","Elizabeth Ozer","Adaptation","Annette Maxwell","Korean","Women","Teen","Hans Diehl","Multi-level Interventions","Chronic","Mary Savoye-DeSanti","Lynne Ornes","Laura Linnan","Weight","Context","RTIPs Meet Up","William Collinge","Richard Rosenkrantz","Lee Ritterband","Frances Thorndike","Affordable Care Act","Kathleen Ell","Radon","Sustainability","Encyclopedia","Lucy Cooke","Mobile Apps","Communities of Color","Erin Mathieu","Sarah Wilcox ","Epidemiology","Underserved","State","Paul Schroy","Reporting","Pap","Jim Annesi","Funding","David Nelson","Brad Hesse","Bob Croyle","Partnerships","Dana-Farber Cancer Institute","Fidelity","African American","Livestrong","Sun Safety","Lori Crane","Robin Vanderpool","Nancy Sherwood","Paul Veugelers","Maureen Lyon","Graham Baker","Amelie Ramirez","Susan Hughes","Basia Belza","Sean Lucan","Philip Huang","Nutrition","OJ Sahler","Karen Weber Cullen","Beth Casey Gold","Michael Potter","Michele Polacsek","Alexander Prokhorov","Sora Tanjasiri","Mary Anne Foo","Marjorie Kagawa-Singer","Wynne Norton","Baretta Casey","Bonnie Spring","Karen Hohrman","Leslie Given","Erin Robinson","Carrie May","Russell Glasgow","Allan Best","Randy Schwartz","Hope Krebill","Jordan Parks","Tookie Bright","Jennifer Redmond","Sharon Straus","Vikram Patel","MOHR"];
	$('#edit-search-block-form--2').autocomplete({
		source: availableTags
	});
	$('.searchField-Tablet #edit-search-block-form--2').autocomplete({
		source: availableTags
	});
}(jQuery));